export const ROUTES = {
  HOME: '/',
  COURSES: '/courses',
  COURSE_DETAIL: (id: string) => `/courses/${id}`,
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  DASHBOARD_LOGIN: '/dashboard/login',
  ADMIN_USERS: '/dashboard/admin/users',
  ADMIN_USER_DETAIL: (id: string) => `/dashboard/admin/users/${id}`,
  ADMIN_CATEGORIES: '/dashboard/admin/categories',
  ADMIN_COURSES: '/dashboard/admin/courses',
  ADMIN_COURSE_DETAIL: (id: string) => `/dashboard/admin/courses/${id}`,
  ADMIN_COURSE_OFFERINGS: '/dashboard/admin/course-offerings',
  ADMIN_COURSE_OFFERING_DETAIL: (id: string) => `/dashboard/admin/course-offerings/${id}`,
  ADMIN_ENROLLMENTS: '/dashboard/admin/enrollments',
  INSTRUCTOR_DASHBOARD: '/dashboard/instructor',
  INSTRUCTOR_COURSE_OFFERINGS: '/dashboard/instructor/course-offerings',
  INSTRUCTOR_COURSE_OFFERING_DETAIL: (id: string) => `/dashboard/instructor/course-offerings/${id}`,
  INSTRUCTOR_ENROLLMENTS: '/dashboard/instructor/enrollments',
  STUDENT_DASHBOARD: '/dashboard/student',
  STUDENT_CLASS: (offeringId: string) => `/dashboard/student/classes/${offeringId}`,
} as const;

